package MercedesResources;



    public class Locators {

        public static final String OUR_MODELS  = "(\"body > div.root.responsivegrid.owc-content-container > div > owc-header\").shadowRoot.querySelector(\"header > div > nav.owc-header__header-navigation > div > ul > li.owc-header-navigation-topic.owc-header-navigation-topic--desktop-nav.owc-header-navigation-topic__model-flyout > button > p\")";
       public static final String HATCHBACK_MODEL = "(\"body > div.root.responsivegrid.owc-content-container > div > owc-header > vmos-flyout\").shadowRoot.querySelector(\"#app-vue > div > ul > li:nth-child(3) > ul > li:nth-child(4) > div\")";
        public static final String A_CLASS_MODEL="(\"body > div.root.responsivegrid.owc-content-container > div > owc-header > vmos-flyout\").shadowRoot.querySelector(\"#app-vue > div > owc-header-flyout > ul > li > ul > li:nth-child(1) > a > p\")";
        public static final String BUILD_CAR="(\"body > div.root.responsivegrid.owc-content-container > div > div > div > owc-stage\").shadowRoot.querySelector(\"div > div.owc-stage__content-wrapper > div > div.owc-stage__cta-wrapper.wb-grid-row > div > div > a.owc-stage-cta-buttons__button.wb-button.wb-button--medium.wb-button--theme-dark.wb-button--large.wb-button--secondary.owc-stage-cta-buttons__button--secondary\")";
        public static final String FUEL_TYPE="(\"body > div.root.responsivegrid.owc-content-container > div > div > div > owcc-car-configurator\").shadowRoot.querySelector(\"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-grid-container.ng-star-inserted > div > div:nth-child(2) > cc-motorization > cc-motorization-filters > cc-motorization-filters-form > form > div > div.cc-motorization-filters-form__primary > div > cc-motorization-filters-primary-filters\")";
        public static final String FILTER_DIESEL_CAR = "(\"body > div.root.responsivegrid.owc-content-container > div > div > div > owcc-car-configurator\").shadowRoot.querySelector(\"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-grid-container.ng-star-inserted > div > div:nth-child(2) > cc-motorization > cc-motorization-filters > cc-motorization-filters-form > form > div > div.cc-motorization-filters-form__primary > div > cc-motorization-filters-primary-filters > div > fieldset > div > ccwb-multi-select > ccwb-checkbox:nth-child(1)\").shadowRoot.querySelector(\"label > div > ccwb-icon\").shadowRoot.querySelector(\"slot > span > svg\")";
        public static final String HIGHEST_PRICE_DIESEL_CAR = "(\"body > div.root.responsivegrid.owc-content-container > div > div > div > owcc-car-configurator\").shadowRoot.querySelector(\"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-grid-container.ng-star-inserted > div > div:nth-child(2) > cc-motorization > cc-motorization-comparison > div > div > div:nth-child(4) > ccwb-card > div.cc-motorization-comparison-header-wrapper > cc-motorization-header > div > div > ccwb-text > span\")";
        public static final String LOWEST_PRICE_DIESEL_CAR = "(\"body > div.root.responsivegrid.owc-content-container > div > div > div > owcc-car-configurator\").shadowRoot.querySelector(\"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-grid-container.ng-star-inserted > div > div:nth-child(2) > cc-motorization > cc-motorization-comparison > div > div > div:nth-child(1) > ccwb-card > div.cc-motorization-comparison-header-wrapper > cc-motorization-header > div > div > ccwb-text > span\")";
    }

